---
- name: prepare docker container for tasks
  hosts: localhost
  user: root
  vars:
      - ansible_python_interpreter: python
      - container_name: testContainer
      - docker_host: "{{ lookup('env','DOCKER_HOST') }}"

  tasks:
    - name: ensure local private key file is protected
      file:
        path: "{{ ansible_env.PWD }}/docker_ansible_client/keys/id_rsa"
        mode: 0600

    - name: delete current container
      docker: >
        name=sonarContainer{{ sonar_version }}
        docker_api_version=1.18
        tls_hostname=localhost
        docker_url={{ docker_host }}
        image=rinderle:testversion
        state=absent

    - name: create client container new
      docker:
        name: sonarContainer{{ sonar_version }}
        docker_api_version: 1.18 # has to be removed on server
        tls_hostname: localhost # has to be removed on server
        docker_url: "{{ docker_host }}"
        image: rinderle:testversion
        detach: False
        hostname: sonarContainer{{ sonar_version }}
        expose: "22,9000"
        ports: "22,9000"
        volumes: "/Users/stefanrinderle/ansibletemp:/tmp/screenshotTempFolder"
        memory_limit: 0
        state: reloaded

    - name: Register ssh port
      # mac osx
      # shell: "docker ps | grep 'sonarContainer{{ sonar_version }}' | grep -Eow '((\\d{5})->22)' | cut -c1-5"
      # server
      shell: "docker ps | grep 'sonarContainer5.1.2' | sed 's/->22.*//' | tail -c 6"
      register: ssh_port

    - debug: msg="Sonarqube running container {{ ssh_port }}"

    - name: add container to the hosts inventory
      add_host:
        hostname: sonarContainer{{ sonar_version }}
        groups: docker
        # mac osx
        #ansible_ssh_host: "192.168.99.100"
        # server
        ansible_ssh_host: "127.0.0.1"
        ansible_ssh_port: "{{ ssh_port.stdout }}"

- name: run the roles inside the client container
  hosts: docker
  remote_user: root

  pre_tasks:

      - name: Install list of packages
        apt: pkg={{item}} state=present
        with_items:
        - unzip
        - openjdk-7-jdk
        - maven
        - git
        - python-pip
        - xvfb
        - firefox
        - graphviz

      - name: create dot symlink
        file: path=/usr/local/bin/dot
              src=/usr/bin/dot
              state=link
              force=yes

  roles:
    - { role: sonar }
    - { role: softVis3dPlugin, sonar_plugin_path: '/opt/sonarqube/extensions/plugins/' }
    - { role: restartSonar }
    - { role: analyse }
    - { role: test }