---
# prepare the sonar environment on a VirtualBox
#

- name: Prepare sonar environment
  hosts: sonarqube-trunk
  user: root
  vars:
    vagrant_priv: "{{ lookup('file', 'files/vagrant/master/keys/vagrant') }}"
    vagrant_pub: "{{ lookup('file', 'files/vagrant/master/keys/vagrant.pub') }}"

  pre_tasks:
  
    - name: Modify hostname
      hostname: name={{ inventory_hostname }}

    - debug: msg="Test sonar trunk"

    - name: Update apt-get repository
      apt: update_cache=yes
      sudo: true

    - name: Upgrade apt-get repository
      apt: upgrade=full
      sudo: true

    - name: Install list of packages
      apt: pkg={{item}} state=present
      with_items:
      - unzip
      - openjdk-7-jdk
      - maven
      - git
      - python-pip
      - xvfb
      - firefox
      - graphviz

    - name: create dot symlink
      file: path=/usr/local/bin/dot
            src=/usr/bin/dot
            state=link
            force=yes

  roles:
#    - { role: ANXS.mysql }
    - { role: sonarTrunk }
#    - { role: softVis3dPlugin, sonar_plugin_path: '/opt/sonarqube/' }
#    - { role: restartSonar, start_command: '/opt/sonarqube/start.sh' }
#    - { role: analyse }
#    - { role: test }

  tasks:
    - shell: echo 'still busy'

  post_tasks:
    - shell: echo 'goodbye'